### ISSUE TITLE
#1 Plant List

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#1]
## Value proposition
As a user
I want to browse a list of plants,
so that I can discover new plants and learn about their care requirements.
## Description

![Image](https://github.com/user-attachments/assets/6ed851f6-3b9d-4cf0-aed1-138997807fb8)

## Acceptance criteria

- [ ] The homepage displays a list of plants.
- [ ] The plant list is headlined with its purpose.
- [ ] Each plant listing includes:
   - [ ] Plant name
   - [ ] Plant botanical name
   - [ ] Plant image
- [ ] The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch feature/plant-list
- [ ]  Inspect and adapt the example data in the [assets folder](https://github.com/neuefische/hh-web-24-8/blob/main/capstone/plant-pal/assets/plants.json)
   - [ ]  Add an imageUrl for each plant, for example from [unsplash](https://unsplash.com/de)
- [ ] create component `PlantCard` to render a list in index.js
- [ ] display plant name, botanical name, plant image on each card
- [ ] create a button "see more" in each card
- [ ] map cards for each plant 
- [ ] add image clearance for host url in next.config.js

**Comment by JessicaLoers** [comment]
Just to mention it, and I think I've mentioned it before: it would be nice if the wireframes used realistic dummy content, like actual plant names.

However, this isn't a big deal, so this user story is approved. ✅🎉
