### ISSUE TITLE
General Styling

### ISSUE THREAD

**Issue by frush86** [ana-nova/plant-pal#11]
## Value proposition
As a user, 
I want a cohesive and user-friendly plant app design
so that I can easily navigate and interact with clear, well-aligned components.

## Description
![Image](https://github.com/user-attachments/assets/11416f55-e2e9-4696-83b3-17693ce31f47)

## Acceptance criteria
- [ ] Update overall color scheme for visual consistency across the app.
- [ ] Update styling for all buttons.
- [ ] Ensure toggle button clearly indicates active and inactive states.
- [ ] Resize form to match plant detail card dimensions for consistency.
- [ ] Right-align favorite and "see more" buttons within the card layout.
- [ ] Add spacing between the footer and the last element in the page for a clean appearance.
- [ ] Change footer buttons to "filled" when on the corresponding page.
- [ ] Remove placeholder text for "fertiliser season" when a new plant is created without fertiliser info.
- [ ] Redefine and update icons representing plant needs for clarity.

## Tasks
- [ ]  Create feature branch feature/global-styling
- [ ] identify all elements that are used in the app and define them in styles.js
- [ ] define unified colors, spacing, size etc. 
- [ ] Implement a better default image for newly created plants.
- [ ] Remove "Shade" option from the PlantForm.
