### ISSUE TITLE
#6 Update Plant

### ISSUE THREAD

**Issue by JessicaLoers** [ana-nova/plant-pal#12]
## Value proposition
As a user
I want to update the details of existing plants,
so that they reflect the most accurate and relevant information.
## Description
![Image](https://github.com/user-attachments/assets/bf507ba9-7eb1-4d30-9b6f-01ea8b46d29b)

## Acceptance criteria

- [ ] Each plant details page includes an easily accessible edit option.
- [ ] Clicking the edit option opens a new page with a form pre-filled with the plant's existing details for modification.
- [ ] The form allows for edits to all plant details, including:
   - [ ] Plant name
   - [ ] Plant botanical name
   - [ ] Plant description
   - [ ] Plant light needs
   - [ ] Plant water needs
   - [ ] Plant fertilizer season
- [ ] The following fields are mandatory:
   - [ ] Plant name
   - [ ] Plant botanical name
   - [ ] Plant light needs
   - [ ] Plant water needs
- [ ] The form section includes options for both saving and cancelling the action.
- [ ] The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- [ ] Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- [ ] Upon confirming the save, the user is immediately redirected to the details page of the edited plant, and the changes are saved and reflected.

## Tasks

- [ ]  Create feature branch feature/update-plant
- [ ]  create an Edit button
- [ ] write function to edit plant data in app.js
- [ ] reuse the form from the PlantForm component to edit given entries
- [ ] set default value of the form to the data of the plant we are editing
