### ISSUE TITLE
Set Custom Reminders

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#14]
## Value proposition
As a user
I want to set custom reminders for plant care tasks,
In order to get notified when a plant needs attention and can keep it healthy

## Description
![Image](https://github.com/user-attachments/assets/c5746a91-99d7-405c-ad85-2bfbf0efb98a)

## Acceptance criteria
- [ ] Users can create a custom reminder for each plant care task by selecting the plant, specifying the task type (e.g. watering, fertilizing), and choosing a due date.
- [ ] The created reminders are shown in their own card down below.
- [ ] Users can repeat or delete a reminder when viewing an existing reminder in the plant details page if the care schedule changes.
- [ ] A notification icon with a red dot is displayed in the footer if there are any pending tasks
- [ ] Clicking the notification icon opens a list of reminder messages within the popup for the plants that need attention.
   - [ ] The notifications are sorted by the due date if users see more than one plant. 
- [ ] Each reminder message shows the plant's name, the care task, and the due date
- [ ] Reminders are displayed until the user marks them as "done" for that day.

## Tasks
- [ ] create a branch feature/custom-reminders
- [ ] create a notification component
   - [ ] Add a UI section in the plant details page where users can set reminders for plant care tasks
   - [ ] Create input fields for specifying the care task (e.g., watering, fertilizing) and due date 
   - [ ] Develop a notification component that displays a red dot icon in the footer when there are pending tasks
- [ ] Create a structure to store reminders with details like plant name, care task, frequency, and due date
- [ ] Write a function to calculate the next due date based on the set frequency

**Comment by JessicaLoers** [comment]
**Hey Team.**

Nice Story - I love the tiny red dot in the wireframe 😁

Refining some of the AC wording to be even more action-oriented can bring the story even more in line with the principles of user-centred design, but that's complaining on a high level. 

> Users can set a custom reminder for each plant, specifying the care task and the due date.
- Users can create a custom reminder for each plant care task by selecting the plant, specifying the task type (e.g. watering, fertilizing), and choosing a due date.

This slight change ensures clarity on the process and user actions for creating reminders.

--- 

> Users can edit or delete an existing reminder if the care schedule changes.
- Users can edit or delete a reminder when viewing an existing reminder in the plant details page if the care schedule changes.

This point may benefit from specific mention of when this option appears to ensures that it's clear where the edit/delete functionality is available.

--- 

> Clicking the notification icon opens a list of reminder messages within the popup for the plants that need attention.

Consider adding criteria that specify if reminders will be sorted by due date or plant name.
