### ISSUE TITLE
Upload Images for Plants

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#15]
## Value proposition
As a user
I want to upload an image for each plant,
so that i can add my personal picture/foto to each plant

## Description
![Image](https://github.com/user-attachments/assets/77675ca0-1322-49d5-a264-247d85df46c1)

## Acceptance criteria
- [ ] the button to add an image should be easily recognizable on the plant details card
- [ ] when clicking the button the user should be able to open a popup
- [ ] the popup frame includes a form to upload an image
- [ ] the user can return from the upload form to the plant details
- [ ] the uploaded image should appear on the plant details page
- [ ] the popup will close after the upload

## Tasks
- [ ] create feature branch `feature/upload-image`
- [ ] create a button in plant details
- [ ] implement cloudinary
- [ ] [cloudinary](https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary)
- [ ] create form to upload an image

**Comment by carmen136** [comment]
Hey team!

I'd like to make some suggestions concerning the Tasks section: 
- you could hide the link to the webdocs for cloudinary like we do it in the slack channels where we combine text and URL (like this: [cloudinary](https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary)), it'd look cleaner
- maybe add a few more descriptive words to your tasks so that the connections between all your tasks and components will be more clear ( e.g. what cloudinary does and where exactly you have to implement it)

**Comment by StephieTack** [comment]
Hi team! When I put in png or jpeg files everything works great! But when I put in a pdf or html-file (I know it's kind of weird) the following occurs: 
PDF:
![Image](https://github.com/user-attachments/assets/20c72963-02ac-43ee-a16e-f2dc4d50a99d)
HTML nothing happens when I click on upload: 
![Image](https://github.com/user-attachments/assets/32c1c0d5-7526-4ae8-9791-a07b7438d311)

I know there was no point for that in your ACs, but maybe you should take it into consideration. You could for example change your code a little bit: `allowed_formats: ["png"] `
:)

**Comment by StephieTack** [comment]
By the way.. this task is marked as "closed"..?

**Comment by frush86** [comment]
Cool. Thanks for the QA we will look at it :)
