### ISSUE TITLE
Organise by Location

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#16]
## Value Proposition
As a user
I want to organize my plants by their needs
in order to  address  each need effectively.

## Description
![Image](https://github.com/user-attachments/assets/f7541e1b-1267-48e2-8316-28872bf73a12)

## Acceptance criteria

- [ ]  user see the needs of the plant on the details page (indoor/outdoor, humidity, temperature need, air draft intolerance).
- [ ]  The user can add new needs for a plant, with options to specify indoor/outdoor suitability, humidity level, temperature range, and air draft tolerance.
- [ ] The user can edit existing needs on the details page through an editable form.
- [ ] Upon saving changes, the updated needs are displayed immediately on the plant’s details page.
- [ ] The user has the option to cancel any changes before saving, which retains the original details.

## Tasks
- [ ]  create feature branch feature/organize-by-location
- [ ]  implement needs of the plant in the form
- [ ] add plant needs.  temp, air-humility and air-draft in plants.js
- [ ]  add category outdoor / indoor  in plants.js

**Comment by Roland-Hufnagel** [comment]
LGTM
