### ISSUE TITLE
#2 Plant Details

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#2]
## Value proposition
As a user
I want to access detailed information about each plant,
so that I can get a better understanding of the plant's needs and care requirements.
## Description
![Image](https://github.com/user-attachments/assets/f69fccf8-fdef-46ef-98a8-733070039621)

## Acceptance criteria

- [ ] Each plant in the plant list has a link to a details page.
- [ ] Each details page contains:
   - [ ] Plant name
   - [ ] Plant botanical name
  - [ ] Plant image
   - [ ] Plant description
   - [ ] Plant light needs
  - [ ] Plant water needs
   - [ ] Plant fertilizer season
- [ ] The water needs, light needs and fertilizer seasons are visualized with fitting icons (e.g. empty or full droplets of water).
- [ ] The detailed view includes a “back” link, allowing users to easily navigate back to the plant list.

## Tasks
- [ ] create feature branch feature/plant-details
- [ ] connect the link button on each card to get to the plant details page
- [ ] create [id] to render a plant details page
- [ ] Link Back Button to Homepage

**Comment by JessicaLoers** [comment]
It’s not entirely clear what links to the details page.

Please add the wireframe that shows the user how to get from the homepage to the details page of the respective plant. 

The easiest solution would be to either use the plant’s name as the link or add a separate “Details” button directly within the card. 🙃
