### ISSUE TITLE
Poisonous Plants / Care Level

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#26]
## Value proposition
As a user
I want to see if a plant is safe for my pet and understand its care level,
So that I can choose plants that are safe for my pet and match my ability to care for them.

## Description
![Image](https://github.com/user-attachments/assets/283c2781-4b68-4971-9f01-93d42d8e54bf)

## Acceptance criteria
- [ ] Poisonous can be added in the form above for cats and dogs
- [ ] Care level can be added in the form under the category additional infos 
  - [ ] ⭐Beginner, Average, Expert
- [ ] Poisonous is displayed on the details page
- [ ] Care difficulty is displayed on the details page under additional infos

## Tasks

- [ ] create new branch feature/care-level
- [ ] Update Form with inputs and value
- [ ] Update [id] with props
- [ ] Update assets/plant.js

**Comment by JessicaLoers** [comment]
**Nice Story.**  🎉

Of cause I have some suggestions for improvement, additional acceptance criteria, and adjustments to ensure it's user-centered and clear. 🫣

But it's only a small change, so the story is approved.

**Value Proposition**
Consider refining the value proposition slightly to make the “why” clearer.

_For example_
**so that I** can choose plants that are safe for my pet and match my ability to care for them. 
>  💡This addition helps emphasize the user’s need for informed decision-making
