### ISSUE TITLE
Get Local Weather

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#28]
## Value proposition
As a user,
I want to see weather alerts on my landing page and receive alerts on "My Owned Plants" page if the weather is unsuitable for my plants,
so I can take appropriate actions if necessary.

## Description
![Image](https://github.com/user-attachments/assets/9abc8707-f3bc-4575-b785-5a3604757306)

## Acceptance criteria

- [ ] Weather information is displayed on the landing page.
- [ ] On the "My Owned Plants" page, user receives an alert if there are severe weather warnings.
- [ ] User can click on the alert icon and receive a proper message about the current weather.
- [ ] User can close the message.
- [ ] If there is no weather warning, user sees no alarm icon.

## Tasks

- [ ] Create a feature branch feature/get-local-weather.
- [ ] Create a weather.js component where the API is fetched:
- [ ] - "https://api.open-meteo.com/v1/forecast?latitude=53.0793&longitude=8.8017&current_weather=true"
- [ ] Return the fetched weather data on the landing page.
- [ ] Lift the weather information state up to App.js.
- [ ] Create icons for visual weather display that change according to the current weather.
- [ ] Create a function that alerts the user if there are severe weather warnings, so they can take care of their outdoor plants.
- [ ] Create a button in the PlantCard of MyPlantsPage that shows a popup with weather warnings when clicked.
- [ ] Implement error handling for fetching weather data.

**Comment by carmen136** [comment]
Hey team! There are some things that can be improved:

- in your value proposition, you only mention information on temperatures you want to implement, but in your acceptance criteria you also talk about humidity information - maybe adjust this in your value prop
- your first acceptance criterion is not very specific: What do you mean by "When an entry is empty [...]"? Also in the same criterion I would paraphrase "...issue with the API..." because in the AC the aim is to avoid developer language and describe functionalities from user's perspective. This applies also on your last acceptance criterion ("when data can't be fetched")
- please check your syntax in this user story, especially in your second to last AC; it is not completely clear what you mean here 
- maybe explain your last dev task a bit further: where or in which cases do you want to implement error handling?
