### ISSUE TITLE
Update Form

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#29]
## Value proposition
As a user 
I want to upload an image when I am creating a new plant
So that I have more personal plant from the beginning.

## Description
![Image](https://github.com/user-attachments/assets/f8c8ba9f-34f4-4703-9a4c-0f7389b1d1db)

## Acceptance criteria
- [ ] The user should see an image upload input in the create/edit plant form
- [ ] The image will be uploaded when submitting the form
- [ ] The uploaded image should appear on the plant details and plant list page

## Tasks
- [ ] create feature branch feature/update-form
- [ ] create file input field for image upload
- [ ] Add an upload section in the form component
- [ ] Add function to show the image on the homepage and the details page

**Comment by carmen136** [comment]
Hey team! Good acceptance criteria, but your dev tasks should be a bit more detailed - e.g. one of the main changes you like to implement (the dropdown menu for additional forms, as I understand it) are not described at all in your tasks.

**Comment by frush86** [comment]
Thank you for taking the time to look at this user story 🚀
We have  a lot of the functionality already in place in our FormComponent so we will just have to switch functions around a bit.
But you are absolutly right. If someone else would start working on this user story more specific tasks would be necessary

**Comment by carmen136** [comment]
I approve your user-story but I'm a bit confused what your main topic is here: from the wireframes and the acceptance criteria it seems like you want to have access to the form with a button on the homepage which leads to a separate page in which the form is placed, but also that you want to adjust the form itself by implementing the additional infos dropdown menu. But in your comment you say that you already have those functionalities already? It probably makes totally sense when you have the whole picture but when only reading the user-story, it is a bit confusing 🙈
