### ISSUE TITLE
#3 Mark Plants as Owned

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#3]
## Value proposition
As a user
I want to mark the plants I own,
so that I can easily track and manage the care of my personal collection.
## Description
![Image](https://github.com/user-attachments/assets/6d7e95e6-5eef-4085-9ef6-014b95688f8b)

## Acceptance criteria

- [ ] Each listed plant includes a “Mark as Owned” option.
- [ ] Clicking the “Mark as Owned” button of an unmarked plant adds it to the “My Plants” list.
- [ ] Clicking the same button again removes the plant from the “My Plants” list.
- [ ] The “My Plants” list is displayed on a separate page dedicated to owned plants.
- [ ] There is a clearly visible link on the homepage to navigate to the “My Plants” page.
- [ ] There is a clearly visible link on the “My Plants” page to navigate back to the homepage.
- [ ] Owned plants are visually highlighted by a distinct icon or style to differentiate them from unowned plants.
- [ ] If there are no owned plants in the “My Plants” list, a message is displayed to the user indicating that no plants have been marked as owned.

## Tasks

- [ ]  Create feature branch feature/mark-as-owned
- [ ]  create mark owned button in PlantCard
- [ ] create function to toggle mark owned button
- [ ] create page myPlants
- [ ] create a Footer component with a Link to Homepage and a Link to My plants

**Comment by JessicaLoers** [comment]
I believe this task might not be necessary for you 🤔

> create error handling to count the number of favorites

Firstly, this operation doesn’t really require error handling, as our data is still local within the project and doesn’t interact with a database. Secondly, the number of favorites isn’t currently displayed anywhere in the UI.

If you intend to display the favorite count, you should add it as an acceptance criterion and represent it in the wireframe as well.
