### ISSUE TITLE
Show random Care Tips 

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#30]
## Value proposition
As a user
I want to see random care tips on the landing page
In order to have more information to take care of my plants
## Description
![Image](https://github.com/user-attachments/assets/eb659442-ac5a-4b40-aed6-b8bb8359b554)

## Acceptance criteria
- [ ] I can see a card on the landing page displaying random care tips.
- [ ] Care tips refresh automatically every 10 seconds.
- [ ] I see 8–10 care tips in total, and each tip is concise and easy to read with a similar word count.

## Tasks
- [ ] create a branch feature/care-tips
- [ ] create a .js file for to store tips 
- [ ] create a function to show tips randomly on the landing page 
- [ ] Use setInterval to refresh the displayed tip every 20 seconds.
- [ ] Create a CareTipsCard component to display the random tip.
