### ISSUE TITLE
customize README.md file

### ISSUE THREAD

**Issue by ana-nova** [ana-nova/plant-pal#44]
## Value proposition
As a project member
I want to create a README file
In order to inform others about the purpose, features, and usage of the project

## Description
The README file provides an overview of the project, including its description, features, technologies and tools.

## Acceptance criteria
- [ ]  The README should include a project title, a brief description of its purpose, features and technologies which were used.
- [ ]  The language should be clear, concise, and professional.
- [ ]  The file should be properly formatted using Markdown.

## Tasks
- [ ] create a branch feature/readme
- [ ] write a brief introduction to the project.
- [ ]  Outline the key features and functionalities.
- [ ]  Ensure the file is reviewed and adheres to Markdown formatting standards.
